name: fms
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  path_provider: ^2.1.5
  fl_chart: 0.71.0
  flutter:
    sdk: flutter
  intl: 0.20.2


  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0           # For Figma-style fonts
  flutter_svg: ^2.0.7            # For using SVG icons from Figma
  # Uncomment if you use navigation or state mgmt:
  # provider: ^6.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "icon.png"

flutter_native_splash:
  color: "#8fffff"           # Background color of splash screen (change if you want)
  image: "icon.png"     # Path to your new splash icon image
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true


flutter:
  uses-material-design: true

  assets:
#    - assets/icons/
#    - assets/images/

#  fonts:
#    - family: Urbanist
#      fonts:
#        - asset: assets/fonts/Urbanist-Regular.ttf
#        - asset: assets/fonts/Urbanist-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/Urbanist-SemiBold.ttf
#          weight: 600
