// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoVhemj_iPkJXkPiZK1QLcnMk-dIY8mOE',
    appId: '1:991589047315:web:b4a5901b2873c2db3ab3e6',
    messagingSenderId: '991589047315',
    projectId: 'spendwell-fms',
    authDomain: 'spendwell-fms.firebaseapp.com',
    storageBucket: 'spendwell-fms.firebasestorage.app',
    measurementId: 'G-4SKD3J2F9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0W20QazFWeOgHnxprzvktIsWosg7MHlI',
    appId: '1:991589047315:android:9a810f8a9aecd6413ab3e6',
    messagingSenderId: '991589047315',
    projectId: 'spendwell-fms',
    storageBucket: 'spendwell-fms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRgM90WBGupmv66XO8LznlojonjbrYYU',
    appId: '1:991589047315:ios:4174f8c52c2ec7673ab3e6',
    messagingSenderId: '991589047315',
    projectId: 'spendwell-fms',
    storageBucket: 'spendwell-fms.firebasestorage.app',
    iosBundleId: 'com.example.fms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWRgM90WBGupmv66XO8LznlojonjbrYYU',
    appId: '1:991589047315:ios:4174f8c52c2ec7673ab3e6',
    messagingSenderId: '991589047315',
    projectId: 'spendwell-fms',
    storageBucket: 'spendwell-fms.firebasestorage.app',
    iosBundleId: 'com.example.fms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoVhemj_iPkJXkPiZK1QLcnMk-dIY8mOE',
    appId: '1:991589047315:web:421f80c9ae61c0743ab3e6',
    messagingSenderId: '991589047315',
    projectId: 'spendwell-fms',
    authDomain: 'spendwell-fms.firebaseapp.com',
    storageBucket: 'spendwell-fms.firebasestorage.app',
    measurementId: 'G-QBESMQKDEK',
  );
}
